apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elgua-pvc
  namespace: bots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elgua-pv
  namespace: bots
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/elgua
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - j4105
            # - key: microk8s.io/cluster
            #   operator: In
            #   values:
            #     - "true"
