apiVersion: apps/v1
kind: Deployment
metadata:
  name: elgua
  namespace: bots
  labels:
    app: elgua
    component: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elgua
      component: bot
  template:
    metadata:
      labels:
        app: elgua
        component: bot
    spec:
      containers:
        - name: elgua
          image: 192.168.1.21:32000/elgua:latest
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
          volumeMounts:
            - mountPath: /cache
              name: elgua-storage
      volumes:
        - name: elgua-storage
          persistentVolumeClaim:
            claimName: elgua-pvc
      nodeSelector:
        kubernetes.io/hostname: j4105

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elgua-pg
  namespace: bots
  labels:
    app: elgua
    component: pg
spec:
  selector:
    matchLabels:
      app: elgua
      component: pg
  serviceName: elgua-pg
  replicas: 1
  template:
    metadata:
      labels:
        app: elgua
        component: pg
    spec:
      containers:
        - name: elgua-pg
          image: postgres:15
          resources:
            limits:
              memory: "256Mi"
              cpu: "150m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: elgua
            - name: POSTGRES_PASSWORD
              value: elgua1234
            - name: POSTGRES_DB
              value: elgua
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: elgua-pg-storage
      volumes:
        - name: elgua-pg-storage
          persistentVolumeClaim:
            claimName: elgua-pg-pvc
      nodeSelector:
        kubernetes.io/hostname: j4105

---
apiVersion: v1
kind: Service
metadata:
  name: elgua-pg
  namespace: bots
spec:
  type: NodePort
  selector:
    app: elgua
    component: pg
  ports:
    - port: 5432
      nodePort: 32754
      protocol: TCP
